lovebegin: 2023-01-01

banner: https://api.toshiki.dev/random.php

# 左边头像的名称
leftname: 安田俊樹
leftavatar: https://q1.qlogo.cn/g?b=qq&nk=1959796501&s=640

# 右边头像的名称
rightname: 李思佳
rightavatar: https://q1.qlogo.cn/g?b=qq&nk=2846931395&s=640


slogan: 💕愿你三冬暖，愿你天不寒🍂

# 站点名称
sitename: 💖那年初夏💖

waline: https://love.comment.toshiki.dev/

theme: koi

lovelist:
  - desc: 一起看日出🌅
    status: 0
    img:
  - desc: 一起看日落🌄
    status: 0
    img:
  - desc: 一起看绚烂的烟花🌟
    status: 0
    img:
  - desc: 一起吃路边摊🍖
    status: 0
    img:
  - desc: 一起唱首歌并录下来🎤
    status: 0
    img:
  - desc: 一起穿情侣装逛街👫
    status: 0
    img:
  - desc: 一起去游乐园（迪士尼）嗨一天🎈
    status: 0
    img:
  - desc: 陪对方过生日🎂
    status: 0
    img:
  - desc: 一起去海南的天涯海角🌴
    status: 0
    img:
  - desc: 一起去你的小学、初中、高中、大学👫
    status: 0
    img:
  - desc: 一起去我的小学、初中、高中、大学👫
    status: 0
    img:
  - desc: 一起放孔明灯🏮
    status: 0
    img:
  - desc: 去遍中国的每一个省份🚉
    status: 0
    img:
  - desc: 一起去钓鱼🐟
    status: 0
    img:
  - desc: 一起去当志愿者、义工👮
    status: 0
    img:
  - desc: 一起坐一辆没坐过的车，在陌生的地方下车逛🚃
    status: 0
    img:
  - desc: 淋一次雨，在雨中漫步☔
    status: 0
    img:
  - desc: 为对方做早餐🍔
    status: 0
    img:
  - desc: 在沙滩上写下彼此的名字✍
    status: 0
    img:
  - desc: 一起看初雪⛄
    status: 0
    img:
  - desc: 穿彼此的衣服👯
    status: 0
    img:
  - desc: 一起去坐过山车🎎
    status: 0
    img:
  - desc: 嘴对嘴吃东西🍜
    status: 0
    img:
  - desc: 一起去游泳🏊
    status: 0
    img:
  - desc: 去遍人民币背后的风景⛳
    status: 0
    img:
  - desc: 两个人一起锻炼运动🏃💃
    status: 0
    img:
  - desc: 一起爬山💑
    status: 0
    img:
  - desc: 在耳边低声旖旎"我爱你"💖
    status: 0
    img:
  - desc: 一起对着流星许愿🌠
    status: 0
    img:
  - desc: 一起手拉手压马路👫
    status: 0
    img:
  - desc: 一起坐在阳台，晒着太阳，磕着瓜子，聊着天👐
    status: 0
    img:
  - desc: 一起养一只宠物🐶
    status: 0
    img:
  - desc: 在公共场合下一起喝娃哈哈🍼
    status: 0
    img:
  - desc: 一起去买菜、做饭、刷碗🍛
    status: 0
    img:
  - desc: 一起去坐热气球🎈
    status: 0
    img:
  - desc: 带我去你童年居住的地方走一走👩
    status: 0
    img:
  - desc: 带你去我童年居住的地方走一走🧑
    status: 0
    img:
  - desc: 一起堆雪人⛄
    status: 0
    img:
  - desc: 一起坐摩天轮，在最高处拥吻💏
    status: 0
    img:
  - desc: 一起用勺子吃西瓜🍉
    status: 0
    img:
  - desc: 一起捡贝壳🐚
    status: 0
    img:
  - desc: 看一次冰灯⛲
    status: 0
    img:
  - desc: 一起去看海🌊
    status: 0
    img:
  - desc: 一起走沙滩🚶
    status: 0
    img:
  - desc: 一起去看支付宝共同种下的树🎋
    status: 0
    img:
  - desc: 一起跨年，通宵守岁📺
    status: 0
    img:
  - desc: 送彼此出门，给一个大大的拥抱与啵啵😚
    status: 0
    img:
  - desc: 一起看书，装满我们的书架💡
    status: 0
    img:
  - desc: 为对方穿衣服、系鞋带🙅
    status: 0
    img:
  - desc: 推对方玩秋千💁
    status: 0
    img:
  - desc: 一起去参加朋友的婚礼💕
    status: 0
    img:
  - desc: 在马尔代夫，体验玻璃地板的海上小屋🏡
    status: 0
    img:
  - desc: 一起坐一次飞机🛫
    status: 0
    img:
  - desc: 一起坐一次游轮🚤
    status: 0
    img:
  - desc: 一起去看一次演唱会🎵
    status: 0
    img:
  - desc: 一起在浴缸里泡澡🛀
    status: 0
    img:
  - desc: 一起去看海豚🐬
    status: 0
    img:
  - desc: 一起去捡落叶🍁
    status: 0
    img:
  - desc: 开车红灯时叫你啵啵🚗
    status: 0
    img:
  - desc: 一起完成一个冒险刺激的挑战💀
    status: 0
    img:
  - desc: 一起沿着铁轨走🚂
    status: 0
    img:
  - desc: 一起去看埃菲尔铁塔，在塔下拥吻👄
    status: 0
    img:
  - desc: 一起设计整理房间💎
    status: 0
    img:
  - desc: 徒步走完北京二环👟
    status: 0
    img:
  - desc: 与好朋友一起，享受四人约会的美妙💜💛💚💙
    status: 0
    img:
  - desc: 为他打领带🔫
    status: 0
    img:
  - desc: 我叫你一次“老婆”，你叫我一次“老公”👨‍❤️‍💋‍👨
    status: 0
    img:
  - desc: 带你在午夜开车兜风🚙
    status: 0
    img:
  - desc: 为她涂指甲油💅
    status: 0
    img:
  - desc: 来一次浪漫的小情趣😍
    status: 0
    img:
  - desc: 在阳台上养着一排多肉植物🥦
    status: 0
    img:
  - desc: 一起过一次六一儿童节👧👦
    status: 0
    img:
  - desc: 入住一次五星级酒店🏨
    status: 0
    img:
  - desc: 为彼此换一个对方心仪的发型，不论长短烫染💇
    status: 0
    img:
  - desc: 偷偷观察对方熟睡的模样，记录下来📷
    status: 0
    img:
  - desc: 一起去打电玩👾
    status: 0
    img:
  - desc: 一起给对方写信，读给对方听📄
    status: 0
    img:
  - desc: 一起滑雪，摔倒也要拉着你🎿
    status: 0
    img:
  - desc: 拥有我们独特的情侣戒指💍
    status: 0
    img:
  - desc: 一起完成一副千片拼图😜
    status: 0
    img:
  - desc: 一起去天安门看升旗仪式🚄
    status: 0
    img:
  - desc: 一起包饺子🥟
    status: 0
    img:
  - desc: 一起去吃自助餐，把没尝过的食材都尝试一遍🔪
    status: 0
    img:
  - desc: 去拍一回写真📸
    status: 0
    img:
  - desc: 一起去新加坡看焰火表演🎇
    status: 0
    img:
  - desc: 一起去看极光⚡⚡
    status: 0
    img:
  - desc: 背着她走一段路👣
    status: 0
    img:
  - desc: 一起赏月🌙
    status: 0
    img:
  - desc: 一起去看樱花🌸
    status: 0
    img:
  - desc: 以喝交杯酒的方式喝东西🥂
    status: 0
    img:
  - desc: 一起买一张彩票🎫
    status: 0
    img:
  - desc: 在树下埋下我们的约定🎑
    status: 0
    img:
  - desc: 带上你我的家人去聚会、旅游🚙
    status: 0
    img:
  - desc: 来一场难忘的求婚🎁💍
    status: 0
    img:
  - desc: 在朋友面前大方介绍彼此💋
    status: 0
    img:
  - desc: 拍属于我们自己的婚纱照🎎
    status: 0
    img:
  - desc: 互相在朋友圈晒结婚证📇
    status: 0
    img:
  - desc: 设计一场梦中的婚礼💤🌹🎉
    status: 0
    img:
  - desc: 拥有一个爱的结晶，给予宝贝最好的爱👶👼
    status: 0
    img:
  - desc: 余生漫漫，执子之手，与子偕老💏
    status: 0
    img: